spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: deploy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher